### ISSUE TITLE
Readme's 'npm install' step result in react error

### ISSUE THREAD

**Issue by stevebriskin** [Circuito-io/ComponentEditor#108]
Node.js v18.15.0 and npm 9.5.0 on MacOS

Following steps in the Readme, the `npm install` step results in this error:
```
124 verbose stack Error: Invalid tag name ">=^16.0.0" of package "react@>=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.
124 verbose stack     at invalidTagName (/opt/homebrew/Cellar/node@18/18.15.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:118:15)
124 verbose stack     at fromRegistry (/opt/homebrew/Cellar/node@18/18.15.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:426:13)
124 verbose stack     at Function.resolve (/opt/homebrew/Cellar/node@18/18.15.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:87:12)
124 verbose stack     at [nodeFromEdge] (/opt/homebrew/Cellar/node@18/18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1068:37)
124 verbose stack     at async [loadPeerSet] (/opt/homebrew/Cellar/node@18/18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1326:23)
124 verbose stack     at async [buildDepStep] (/opt/homebrew/Cellar/node@18/18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
124 verbose stack     at async Arborist.buildIdealTree (/opt/homebrew/Cellar/node@18/18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
124 verbose stack     at async Promise.all (index 1)
124 verbose stack     at async Arborist.reify (/opt/homebrew/Cellar/node@18/18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
124 verbose stack     at async Install.exec (/opt/homebrew/Cellar/node@18/18.15.0/lib/node_modules/npm/lib/commands/install.js:146:5)
```

Googling around, I found https://github.com/ReactTooltip/react-tooltip/issues/661 and its `--legacy-peer-deps` recommendation did the trick for me. The Readme should either be updated with this or the react-tooltip version should be bumped.

**Comment by josemqz** [comment]
Yep, still happening. I hope this gets some attention, because it's a pretty small problem.

**Comment by eyak** [comment]
Thank you for that!
